### ISSUE TITLE
Wrong number of arguments

### ISSUE THREAD

**Issue by ivan-cukic** [mikemcquaid/ManningAsciiDoc#5]
Hi, I'm trying to generate html5 and docbook from your examples (latest master, nothing changed).

I'm getting the following error (similar for html5):

```
$ rake docbook --trace
** Invoke docbook (first_time)
** Invoke /media/ivan/projects/functional-cpp/book/output/book.xml (first_time)
** Invoke /media/ivan/projects/functional-cpp/book/input/Title.adoc (first_time, not_needed)
** Invoke /media/ivan/projects/functional-cpp/book/output/00-SamplePreface.xml (first_time)
** Invoke input/00-SamplePreface.adoc (first_time, not_needed)
** Invoke /media/ivan/projects/functional-cpp/book/output/manning-book.xsd (first_time, not_needed)
** Invoke output (first_time, not_needed)
** Execute /media/ivan/projects/functional-cpp/book/output/00-SamplePreface.xml
asciidoctor: generating /media/ivan/projects/functional-cpp/book/output/00-SamplePreface.xml
rake aborted!
ArgumentError: wrong number of arguments (2 for 1)
/media/ivan/projects/functional-cpp/book/asciidoctor_extensions/manning_postprocessor.rb:12:in `process'
/usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:1034:in `[]'
/usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:1034:in `block in convert'
/usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:1033:in `each'
/usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:1033:in `convert'
/usr/lib/ruby/vendor_ruby/asciidoctor.rb:1499:in `convert'
/media/ivan/projects/functional-cpp/book/Rakefile:98:in `asciidoctor'
/media/ivan/projects/functional-cpp/book/Rakefile:132:in `block in <top (required)>'
/usr/lib/ruby/2.2.0/rake/task.rb:238:in `call'
/usr/lib/ruby/2.2.0/rake/task.rb:238:in `block in execute'
/usr/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/usr/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/usr/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => docbook => /media/ivan/projects/functional-cpp/book/output/book.xml => /media/ivan/projects/functional-cpp/book/output/00-SamplePreface.xml
```

**Comment by mikemcquaid** [comment]
Are you sure you have run `bundle install` correctly? I can reproduce this if I `bundle update asciidoc` but not with an unchanged `master` checkout.

**Comment by ivan-cukic** [comment]
Yes. I did it on two separate systems (different distributions and all).

If I find out something more, I'll update the report.

**Comment by mikemcquaid** [comment]
I believe this should be fixed as of #6. If not: shout and I'll try something else.

**Comment by ivan-cukic** [comment]
Confirmed. Thanks! (and thanks for maintaining the project like this!)

**Comment by mikemcquaid** [comment]
My pleasure. Thanks for the report! Still not sure what happened there!
